name: Preview PR request
on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pull-requests: write
  issues: write # Add this permission
  actions: read
  statuses: write

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.132.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Setup Hugo
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo --gc --minify
      - name: Comment PR
        uses: actions/github-script@v7
        if: always()
        with:
          script: |
            try {
              const message = `Hugo build status: ${process.env.STATUS}
              
              Build completed with ${process.env.STATUS === 'success' ? '✅' : '❌'}`;
              
              await github.rest.issues.createComment({
                ...context.repo,
                issue_number: context.issue.number,
                body: message
              });
            } catch (error) {
              console.error('Failed to create comment:', error);
              core.setFailed(error.message);
            }
        env:
          STATUS: ${{ job.status }}
