name: Preview PR request
on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pull-requests: write
  issues: write # Add this permission
  actions: read
  statuses: write

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run GitHub Script
        uses: actions/github-script@v7
        with:
          script: |
            const { github, context } = require('@actions/github');
            const issue_number = context.issue.number;
            const comment = "Hugo build status: failure\n\nBuild completed with ❌";
            await github.issues.createComment({
              ...context.repo,
              issue_number,
              body: comment
            });
